"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$c6#p&et4mmx1684)x9p*g1el4)^1x557@x4uy7&7#fnik@fsj'

# SECURITY WARNING: don't run with debug turned on in production!

#DEBUG=TRUE=개발모드, FALSE=운영모드
DEBUG = True

#서버의 IP or 도메인 지정
#개발 모드 경우엔 값 지정 안해도 ['localhost,'127.0.0.1']로 간주
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'bookmark.apps.BookmarkConfig',
    'blog.apps.BlogConfig',
    'mysite',
    'taggit.apps.TaggitAppConfig',
    'taggit_templatetags2',
    'photo.apps.PhotoConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        #원래 적힌간 장고 자체 템플릿 엔진
        #django.template.backends.jinja2.Jinja2
        #파이썬 언어의 대표 템플릿 엔진
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS-프로젝트 템플릿 파일이 위치할 디렉터리 지정
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        #앺플리케이션 내 템플릿 디렉토리에서도 찾을지 여부
        'APP_DIRS': True,
        #
        'OPTIONS': {
            #웹요청에 있는 파라미터들을 인자로 받아서
            #컨첵스트 데이터로 사용될 사전을 만드는/ 호출 가능한 객체를 지정
            #반환하는 사전은 최종 컨텍스트 데이터를  만들때 추가ㅣ
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

#프로젝트 정적 파일이 위치팔 디렉ㅌ리-직접정의 해야함
STATICFILES_DIRS = [os.path.join(BASE_DIR,'templates')]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT= os.path.join(BASE_DIR,'media')


DISQUS_SHORTNAME = 'pydjango-study-web'
DISQUS_MY_DOMAIN = 'http://127.0.0.1:8000/'

# LOGIN_URL= '/account/login'
LOGIN_REDIRECT_URL='/'